### ISSUE TITLE
[BUG] Fails on debian 11 (no python-mysqldb package)

### ISSUE THREAD

**Issue by rgdev** [idealista/mysql_role#76]
### Description

On a Debian 11 target the role fails as it can't find the `python-mysqldb` package.

It seems it has been replaced by [python3-mysqldb](https://packages.debian.org/bullseye/python/python3-mysqldb).

### Steps to Reproduce

Build a simple playbook and run it on a to install MySQL on Debian 11 server.

Playbook : 
```
---
- hosts: provision
  vars_files:
    - vars/mysql.yml
  become: true
  roles:
    - role: idealista.mysql_role
```
Vars : 
```
mysql_databases:
   - name: example_DB
     encoding: utf8

mysql_users:
   - name: admin
     host: '*'
     password: secret
     priv: [ '*.*:USAGE' ]
```
Result : 
```
$ ansible-playbook -K --ask-pass -i hosts -u XXXXXX deploy-mysql-server.yml

PLAY [provision] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************
ok: [test-ansible-mysql]

TASK [idealista.mysql_role : MySQL | Install] ******************************************************************************************************************************************************
included: .../roles/idealista.mysql_role/tasks/install_mysql.yml for test-ansible-mysql

TASK [idealista.mysql_role : MySQL | Gather OS specific variables] *********************************************************************************************************************************
ok: [test-ansible-mysql]

TASK [idealista.mysql_role : MySQL | Installing dependencies] **************************************************************************************************************************************
fatal: [test-ansible-mysql]: FAILED! => {"changed": false, "msg": "No package matching 'python-mysqldb' is available"}

PLAY RECAP *****************************************************************************************************************************************************************************************
test-ansible-mysql         : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Expected behavior:**
Proper MySQL Server installation

**Actual behavior:**
Fails while trying to install dependencies

**Reproduces how often:** 
100%

### Environment

- The release version/s you are using: 
- OS: Debian MacOS 11.6 (local), Debian 11 (remote)
- Ansible Version: 2.10.5
- Python Version: 2.7.16 / 3.9.7 (local), 3.9.2 (remote)
